### ISSUE TITLE
Random number generator behave differently from original Lua code

### ISSUE THREAD

**Issue by SLED-5** [SLED-5/23Spring-ASE#7]
There's something wrong with our random generator.

- The output is different from Lua (use `print()` to observe this)
- `for i in range(1, 100):
		num1.add(rand(0,1))
		num2.add(rand(0,1))` is not working. The output stays the same no matter what's the range

**Comment by yangzhijin4** [comment]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/37759152/212978613-ef66d5ad-3a85-495f-ae51-2a11a45ca230.png">
Yea, just saw this issue, trying to figure it out.

**Comment by SLED-5** [comment]
fixed in latest commit
